### ISSUE TITLE
Godot -Camera branch has a memory leak.

### ISSUE THREAD

**Issue by Fel-2** [pkowal1982/DeepSpaceImmersion#1]
I added the camera texture to a 3d cube and from my observation the memory usage staidly rises until the camera stops working and godot crashes. 
Sorry for making the issue here I couldn't find where to make the issue on your godot repo.

**Comment by pkowal1982** [comment]
Can you share your project and write more about testing process / environment?

**Comment by Fel-2** [comment]
## Memory leak in godot camera branch

### Description
Adding the camera material in a 3d scene on any object causes a memory leak.
### Steps to Reproduce
1. Making a 3d node
2. Adding camera texture to albedo of 3d object
3. Observing memory usage godot memory usage increases by 1GB every 10-15 seconds 


### Screenshots
![image](https://github.com/pkowal1982/DeepSpaceImmersion/assets/51909835/12be58d6-257b-4e4d-a978-8f5d0bd85b6a)
### Environment
- Godot Version: 4.3.dev Camera Branch
- Operating System: Arch Linux X11
- Kernel: 6.7.5
- PC-Specs
  - CPU: AMD Ryzen 5 5600X (12) @ 3.700GHz 
   - GPU: NVIDIA GeForce RTX 4060 Ti 16GB 
    - Memory: 32015MiB 
---

#### Godot Project Repository
[Godot project repository](https://github.com/Exw27/Godot-WebCam)

**Comment by pkowal1982** [comment]
Checked it and I can confirm that there's a memory leak.
Not sure how to fix it as this is caused by [this line](https://github.com/godotengine/godot/blob/81f3d43cc1ba01136795fb2059bbaa55bc514a16/servers/camera/camera_feed.cpp#L187) and I did not touch it.
Still I think it would be good if you left the comment in [the original PR](https://github.com/godotengine/godot/pull/53666).

**Comment by Fel-2** [comment]
> Checked it and I can confirm that there's a memory leak.
> Not sure how to fix it as this is caused by [this line](https://github.com/godotengine/godot/blob/81f3d43cc1ba01136795fb2059bbaa55bc514a16/servers/camera/camera_feed.cpp#L187) and I did not touch it.
> Still I think it would be good if you left the comment in [the original PR](https://github.com/godotengine/godot/pull/53666).

Will do that.
Thanks.

**Comment by pkowal1982** [comment]
Thanks for comment in PR. :)
